"""Add file_data to Note

Revision ID: 3a2a0a8e0c94
Revises: 5cc4cab3796d
Create Date: 2025-06-17 00:01:50.380512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a2a0a8e0c94'
down_revision = '5cc4cab3796d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_data', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_column('file_data')

    # ### end Alembic commands ###
