"""Added share_token, share_expiry, views_left to Note

Revision ID: 4fe3d61a0e53
Revises: 3a2a0a8e0c94
Create Date: 2025-06-20 11:05:51.187416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fe3d61a0e53'
down_revision = '3a2a0a8e0c94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('share_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('share_expiry', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('views_left', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['share_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('views_left')
        batch_op.drop_column('share_expiry')
        batch_op.drop_column('share_token')

    # ### end Alembic commands ###
